version: '3'
services:

  back:
    restart: always
    environment:
      CLIENT: "http://localhost:5173"
      PORT: "5000"
      DB_PASSWORD: "securepassword"
      DB_HOST: "rc1a-8cgm2ii401pwhc7x.mdb.yandexcloud.net"
      DB_PORT: "6432"
      DB_USER: "avito"
      DB_NAME: "matrix"
      COST_SERVER: "http://10.2.0.10:5001"
    build:
        context: ./backpurplehack
        dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      front:
        condition: service_started

  front:
    environment:
      VITE_API_URL: "http://localhost:5000/"
    build:
      context: ./frontpurplehack
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

  costs:
    environment:
      ADMIN_SERVER: "http://localhost:5000"
      PORT: "5001"
      DB_PASSWORD: "securepassword"
      DB_HOST: "rc1a-8cgm2ii401pwhc7x.mdb.yandexcloud.net"
      DB_PORT: "6432"
      DB_USER: "avito"
      DB_NAME: "matrix"
    build:
      context: ./serviceCost
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      back:
        condition: service_started
      front:
        condition: service_started
